### ISSUE TITLE
Wrapped LicenseParam in v1.29

### ISSUE THREAD

**Issue by nikolakurtic** [christian-schlichtherle/truelicense#11]
Hi again :)

If I have wrapped LicenseParam class as
`public interface ValidatingLicenseParam extends LicenseParam {
    Collection<Restriction> getRestrictions();
}`
and I use it to create LicenseManager, collection of `Restriction` is stored in license but in v4.0.3 I cannot access it while loading. Is there a way to access this field?
Thanks!

**Comment by christian-schlichtherle** [comment]
I need more details to reproduce your issue, please.

**Comment by christian-schlichtherle** [comment]
Can I close this issue?
