### ISSUE TITLE
Old documentation site certificate issue

### ISSUE THREAD

**Issue by ghost** [christian-schlichtherle/truelicense#14]
The old documentation site (https://truelicense.net/) is soft-blocked by Firefox with a certificate security warning:

> Web sites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for truelicense.net. The certificate is only valid for the following names: *.github.com, github.com
>  
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by christian-schlichtherle** [comment]
Hi Mike,

there is hardly any content left on the old site which hasn’t been edited and published again on the new site. It’ only some information about upgrading older projects. As soon as I have edited and published everything the old site will be simply shut down.

In the mean time, if you really want to visit the old site, you can use http://truelicense.net <http://truelicense.net/> .

Kind regards,
Christian

**Comment by ghost** [comment]
Yes it was the migration information I was interested in. I think it would be great for that to be on the new site as it is useful! Thanks for letting me know.
