### ISSUE TITLE
How to use consumerAmount?

### ISSUE THREAD

**Issue by 549393092** [christian-schlichtherle/truelicense#3]
When create *.lic file, we can write some content, one of the attribute is consumerAmount. However, I cannot find any useful documentation about it.
As I assume, it will restrict user count to be allowed to use the system, is that right?

**Comment by christian-schlichtherle** [comment]
Sorry for the late response:

This property is intended for future extension: You can set it to any positive value, but it doesn't have any effect. This property is intended to be used with floating licenses, but the logic required to implement this feature requires access to some central license server, which isn't implemented yet.

You can keep this issue open to track this feature request, but I'm not able to provide any ETA.

**Comment by 549393092** [comment]
Got it. Thanks!
