### ISSUE TITLE
the document  website  dead

### ISSUE THREAD

**Issue by QingMings** [christian-schlichtherle/truelicense#36]
![image](https://github.com/christian-schlichtherle/truelicense/assets/22107668/cb25f700-0fbb-4e0a-9279-31edbd0f69f5)

I was able to access the document website normally yesterday, but suddenly it's not working today

**Comment by christian-schlichtherle** [comment]
I'm sorry, there was a configuration error when transferring the domain. The issue has been fixed, please try again. Please note that it can take some hours before the change in the DNS has been propagated to your system.
